# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
spring:
  application:
    name: micro-service-domain-archetype
  main.banner-mode: off
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/archetype
    username: ENC(ku7ULo35PR0vtzrDInm9YZe0l3cz6Z2rp2ON6YD2lKdNOmj2rzmdwlyr6PdRj5gg)
    password: ENC(17Atuv7t31S12Oz8kBXTfyTTVt6GYNDr6ousctZdQ2TK/5TcRbpUoo5pEBdvb4J5)
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline: 0
# ===================================================================
# ZIPKIN PROPERTIES
# ===================================================================
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  pattern:
    file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'
    console: "%p [${spring.application.name:}, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L, %X{mdc.uuid}, %m%n%ex{3}"
  level:
    com.moontech: DEBUG
    org:
      springframework.data: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

# ===================================================================
# URL ENDPOINTS
# ===================================================================
api:
  uri:
    domain:
      users: /users
    data:
      modified: /{id}
      search: /{search}
      authentication: /authentication
      confirm: /confirm
      passwordForgot: /password/reset
  interceptorPath: "/**"
# ===================================================================
# SWAGGER PROPERTIES
# ===================================================================
swagger:
  basePackage: com.moontech
  title: SERV-archetype-service
  descriptionApi: Arquetipo para micro servicios
  version: 1.0.0
  nameDeveloper: Felipe Monzón, Paul quintero
  contactUrl: https://felipemonzon.github.io/
  emailDeveloper: felipemonzon2705@gmail.com
  licenceType: MIT LICENCE
  licenceUrl: https://github.com/felipemonzon/sales-point-service/blob/main/LICENSE


quick:
  api:
    parent:
      basePackage: com.moontech.archetype
    package:
      controller: infrastructure.apis
      service: application.service
      entity: domain.entity
      repository: domain.repository